# Generated by Django 2.2.12 on 2020-05-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igrac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disclaimerlicensepage',
            name='intro',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
